/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ngo;

/**
 *
 * @author ash
 */
public class NwUser extends javax.swing.JPanel {

    /**
     * Creates new form NwUser
     */
    public NwUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/ash/Downloads/NGO files/images1.jpeg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 260, 240);

        jButton1.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jButton1.setText("Pledge Donation");
        jButton1.setToolTipText("Pledge a specific amount to donate after certain time ");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 140, 180, 50);

        jButton2.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jButton2.setText("Donate Normally");
        jButton2.setToolTipText("Donate without pledging any amount");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 300, 180, 50);

        jButton3.setFont(new java.awt.Font("Purisa", 0, 15)); // NOI18N
        jButton3.setText("Anonymous Donor");
        jButton3.setToolTipText("User can donate anonymously ");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 300, 180, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ash/Downloads/NGO files/index.jpeg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(550, 90, 180, 280);

        jButton5.setText("<= Back to Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(590, 0, 140, 29);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 730, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
